#' en - animals
#'
#' data frame of words and clues
#'
#' @docType data
#'
#' @rdname word_lists
#'
#' @export
#'
cw_wordlist_animal_en <-
  data.frame(
    words =
      c("alligator", "alpaca", "ant", "antelope", "ape",
        "armadillo", "donkey", "baboon", "badger", "bat",
        "bear", "beaver", "bee", "beetle", "buffalo", "butterfly", "camel",
        "carabao", "caribou", "cat", "cattle", "cheetah",
        "chimpanzee", "chinchilla", "cicada", "clam", "cockroach", "cod",
        "coyote", "crab", "cricket", "crow", "raven", "deer", "dinosaur",
        "dog", "dolphin", "duck", "eel", "elephant", "elk",
        "ferret", "fish", "fly", "fox", "frog", "toad", "gerbil", "giraffe",
        "gnat", "gnu", "goat", "goldfish", "gorilla", "grasshopper",
        "guineapig", "hamster", "hare", "hedgehog", "herring", "hippopotamus",
        "hornet", "horse", "hound", "hyena", "impala", "insect", "jackal",
        "jellyfish", "kangaroo", "koala", "leopard", "lion",
        "lizard", "llama", "locust", "louse", "mallard", "mammoth", "manatee",
        "marten", "mink", "minnow", "mole", "monkey", "moose", "mosquito",
        "mouse", "rat", "mule", "muskrat", "otter", "ox", "oyster", "panda",
        "pig", "platypus", "porcupine", "prairiedog",
        "pug", "rabbit", "raccoon", "reindeer", "rhinoceros", "salmon",
        "sardine", "scorpion", "seal","sealion", "serval", "shark", "sheep",
        "skunk", "snail", "snake", "spider", "squirrel", "swan", "termite",
        "tiger", "trout", "turtle","tortoise", "walrus", "wasp", "weasel",
        "whale", "wolf", "wombat", "woodchuck", "worm", "yak", "yellowjacket",
        "zebra"),

    clues =
      c(
        "Predatory, semiaquatic reptile",
        "Llama like inhabitant of the Andes",
        "Small with mandibles and antenna",
        "Even-toad hoofed animal which is neither sheep, cattle, nor goat",
        "Tailless humanlike primate",
        'A "little armoured one"',
        "Long eared work animal",
        "Big non-humanoid primate-",
        "badger",
        "bat",
        "bear",
        "beaver",
        "Striped but no predator",
        "beetle",
        "buffalo",
        "butterfly",
        "camel",
        "carabao",
        "caribou",
        "cat",
        "cattle",
        "cheetah",
        "chimpanzee",
        "chinchilla",
        "cicada",
        "clam",
        "cockroach",
        "cod",
        "coyote",
        "clawed and armored sidewalker",
        "cricket",
        "crow",
        "raven",
        "deer",
        "dinosaur",
        "dog",
        "dolphin",
        "duck",
        "Elongated fish",
        "Vegitarian mammal with trunk and tusks",
        "elk",
        "ferret",
        "fish",
        "fly",
        "fox",
        "frog",
        "toad",
        "gerbil",
        "giraffe",
        "gnat",
        "gnu",
        "goat",
        "goldfish",
        "Largest primate",
        "grasshopper",
        "Rodent living in Andes",
        "hamster",
        "Fast runner with long ears",
        "hedgehog",
        "herring",
        "hippopotamus",
        "hornet",
        "horse",
        "hound",
        "hyena",
        "impala",
        "insect",
        "Medium-sized omnivorous mammal",
        "jellyfish",
        "Australian original",
        "koala",
        "leopard",
        "lion",
        "lizard",
        "llama",
        "locust",
        "louse",
        "mallard",
        "mammoth",
        "manatee",
        "marten",
        "mink",
        "Bait fish",
        "mole",
        "monkey",
        "moose",
        "mosquito",
        "mouse",
        "rat",
        "mule",
        "muskrat",
        "otter",
        "Castrated adult male cattle",
        "oyster",
        "panda",
        "Big omnivore mammal",
        "platypus",
        "porcupine",
        "prairiedog",
        "pug",
        "rabbit",
        "raccoon",
        "reindeer",
        "rhinoceros",
        "Strong swimmer and jumper",
        "sardine",
        "scorpion",
        "seal",
        "sealion",
        "serval",
        "shark",
        "sheep",
        "skunk",
        "Slow but armored",
        "snake",
        "Eight legged",
        "squirrel",
        "swan",
        "Living in colonies",
        "tiger",
        "trout",
        "turtle",
        "Armored reptile",
        "walrus",
        "wasp",
        "Small, slender predator",
        "whale",
        "wolf",
        "wombat",
        "woodchuck",
        "worm",
        "yak",
        "yellowjacket",
        "zebra"
      )
  )
